DROP DATABASE IF EXISTS JUEGO;
CREATE DATABASE JUEGO;

USE JUEGO;

CREATE TABLE JUGADORES(
	ID INT PRIMARY KEY NOT NULL,
	NOMBRE TEXT NOT NULL,
	USUARIO TEXT PRIMARY KEY NOT NULL,
	PASSWORD TEXT NOT NULL,
	EDAD INT NOT NULL,
	PUNTUACION INT,
	VICTORIAS INT
)ENGINE = InnoDB;

CREATE TABLE  PARTIDAS(
	ID INT PRIMARY KEY NOT NULL,
	DURACION INT NOT NULL,
	GANADOR INT NOT NULL,
	FECHA DATETIME NOT NULL --lo dejo vacio para que se rellene solo al hacer los inserts
)ENGINE = InnoDB;

CREATE TABLE ENFRENTAMIENTOS(
	ID_1 INT NOT NULL,
	ID_2 INT NOT NULL,
	PARTIDA INT NOT NULL,
	PUNTUACION INT,
	VICTORIAS INT
)ENGINE = InnoDB;

INSERT INTO JUGADORES VALUES(1,'JAN','JANNOG','CONTRASEÑA123', 21, 5630, 10);
INSERT INTO JUGADORES VALUES(2,'GERARD','ALV45','PAPASITORICO', 20, 2960, 6);
INSERT INTO JUGADORES VALUES(3,'ERIC','ERLEON','SALCHIPAPA', 20, 495, 2);

INSERT INTO PARTIDAS VALUES(1,124, 1);
INSERT INTO PARTIDAS VALUES(2,150, 2);
INSERT INTO PARTIDAS VALUES(3,40, 1);
INSERT INTO PARTIDAS VALUES(4,66, 3);
INSERT INTO PARTIDAS VALUES(5,98, 1);

INSERT INTO ENFRENTAMIENDOS VALUES(1,2,1,2394);
INSERT INTO ENFRENTAMIENDOS VALUES(2,3,2,3234);
INSERT INTO ENFRENTAMIENDOS VALUES(1,3,3,5634,);
INSERT INTO ENFRENTAMIENDOS VALUES(2,3,4,1234);
INSERT INTO ENFRENTAMIENDOS VALUES(1,2,5,2343);